import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
//import './globals.css'
import "@/styles/globals.css"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import React, {Suspense} from 'react'
import Loading from './loading'
import Sidebar from './page'
// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
 
export default function RootLayout({ 
  children,
 }: {children: React.ReactNode}) {
  return (
          <Sidebar>{children}</Sidebar>
  )
}
